name: Build & Run Tests

on:
  pull_request:
    branches: [ "main", "dev" ]
  workflow_dispatch:

jobs:
  build-and-test:
    strategy:
      matrix:
        os: [ubuntu-latest]
        config: [Debug, Release]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Initialize submodules
        run: git submodule update --init --recursive

      - name: Configure CMake
        shell: bash
        run: |
          cmake -S . -B build -DCMAKE_BUILD_TYPE=${{ matrix.config }}

      - name: Build Tests
        shell: bash
        run: |
          cmake --build build --target Tests --parallel

      - name: Run Tests
        shell: bash
        working-directory: build
        run: |
          ctest -R Tests --output-on-failure